import{b as l,c as S,d as N,e as T,f as R,g as _}from"./chunk-PFXBJ476.js";import{Aa as M,G as b,Ja as y,Pa as r,Qa as n,S as C,Sa as j,Wa as o,Ya as x,a as h,b as p,i as g,j as c,p as d,sa as a,sb as w,w as s,x as f,z as E}from"./chunk-3HNIGLXE.js";var m=class u{#e=C(w);numErrors=l(this.#e.getErrorCount$,{initialValue:0});something=new g(1);debounce$=this.something.pipe(E(300));myGuess=5;#t=this.debounce$.pipe(s(e=>Math.floor(e)===e),s(e=>e>=1&&e<=100),b((e,t)=>t<e.left||t>e.right?e:t<this.myGuess?{left:t,right:e.right,guess:t}:t>this.myGuess?{left:e.left,right:t,guess:t}:p(h({},e),{guess:t}),{left:1,right:100,guess:-1}),d(({left:e,right:t,guess:i})=>{if(i===this.myGuess)throw new Error("Error is thrown and the global error handler handles it");return`Guess an integer between ${e} and ${t}`}),f(e=>(console.error(e),this.#e.addNumErrors(),alert(`Number of error caught: ${this.numErrors()}`),c)));hint=l(this.#t,{initialValue:"Guess an integer between 1 and 100"});static \u0275fac=function(t){return new(t||u)};static \u0275cmp=M({type:u,selectors:[["app-reject-errors-example"]],decls:11,vars:2,consts:[["type","number",3,"ngModelChange","ngModel"]],template:function(t,i){t&1&&(r(0,"h3"),o(1,"With rejectErrors option removed, toSignal catches the uncaught exception and handles it explicitly."),n(),r(2,"p"),o(3,"The observable's catchError operator returns EMPTY to complete the observable."),n(),r(4,"p"),o(5,"Subsequent input to the textbox has no effect."),n(),r(6,"div")(7,"p"),o(8),n()(),o(9," Your guess: "),r(10,"input",0),j("ngModelChange",function(G){return i.something.next(G)}),n()),t&2&&(a(8),x("Hint: ",i.hint()),a(2),y("ngModel",i.something.getValue()))},dependencies:[_,S,R,N,T],styles:["button[_ngcontent-%COMP%]{margin-right:1rem;padding:.5rem}"],changeDetection:0})};export{m as default};
